from __future__ import annotations

SEED = 20260411
ARTIFACT_VERSION = 2
MIN_ROLE_COHORT = 8
BOOTSTRAP_ITERATIONS = 200

REQUIRED_COLUMNS = [
    "Inf",
    "Player",
    "Nation",
    "Club",
    "Position",
    "Age",
    "Ability",
    "Potential",
    "Transfer Value",
    "Wage",
    "AT League Goals",
    "Recommendation",
    "Pres A",
    "Poss Won/90",
    "K Tck/90",
    "K Tck",
    "Itc",
    "Int/90",
    "Clr/90",
    "Clearances",
    "Blk/90",
    "Pres A/90",
    "Pres C",
    "Pres C/90",
    "Shts Blckd/90",
    "Tck R",
    "Tck A",
    "Tck C",
    "Tck/90",
    "Shts Blckd",
    "Blk",
    "Shot/90",
    "Shot %",
    "ShT/90",
    "ShT",
    "Shots From Outside The Box Per 90 minutes",
    "Shots",
    "Goals From Outside The Box",
    "Free Kick Shots",
    "xG/shot",
    "Conv %",
    "Svt",
    "Svp",
    "Svh",
    "Sv %",
    "xSv %",
    "xGP/90",
    "xGP",
    "PsP",
    "Poss Lost/90",
    "Ps C/90",
    "Ps C",
    "Ps A/90",
    "Pas A",
    "Pas %",
    "OP-KP/90",
    "KP/90",
    "Key",
    "CCC",
    "Ch C/90",
    "Pr passes/90",
    "Asts/90",
    "Off",
    "Sprints/90",
    "Drb/90",
    "Saves/90",
    "Drb",
    "Dist/90",
    "Distance",
    "MLG",
    "Yel",
    "xG",
    "Tcon/90",
    "Red cards",
    "Pts/Gm",
    "PoM",
    "Pen/R",
    "Pens S",
    "Pens Saved Ratio",
    "Pens Saved",
    "Pens Faced",
    "Pens",
    "NP-xG/90",
    "NP-xG",
    "Mins/Gm",
    "Minutes",
    "Goals per 90 minutes",
    "Goals Conceded",
    "Goals",
    "Game Win Ratio",
    "Fouls Made",
    "Fouls Against",
    "xG/90",
    "xG-OP",
    "xA/90",
    "xA",
    "Con/90",
    "Cln/90",
    "Clean Sheets",
    "Rating",
    "Mins/Gl",
    "Assists",
    "OP-Crs C",
    "OP-Crs A",
    "Cr C",
    "Cr A",
    "Hdrs",
    "Hdrs A",
    "Hdr %",
    "Preferred Foot",
    "Right Foot",
    "Left Foot",
    "Height",
    "OP-Cr %",
    "Appearances",
    "OP-Crs C/90",
    "OP-Crs A/90",
    "Hdrs L/90",
    "Cr C/90",
    "Crs A/90",
    "Cr C/A",
    "AT League Apps",
    "AT Gls",
    "AT Apps",
    "K Hdrs/90",
    "Hdrs W/90",
    "Aer A/90",
    "Actual Playing Time",
]

IDENTIFIER_COLUMNS = {
    "Inf",
    "Player",
    "Nation",
    "Club",
    "Position",
    "Preferred Foot",
    "Right Foot",
    "Left Foot",
}

LEAKAGE_COLUMNS = {"Ability", "Potential", "Recommendation", "Rating"}
MARKET_COLUMNS = {"Transfer Value", "Wage"}
HISTORICAL_COLUMNS = {"AT League Goals", "AT League Apps", "AT Gls", "AT Apps"}
CONTEXT_COLUMNS = {"Pts/Gm", "Minutes", "Appearances", "Mins/Gm", "Actual Playing Time", "Age"}

NEGATIVE_ORIENTATION = {
    "Poss Lost/90",
    "Fouls Made",
    "Yel",
    "Red cards",
    "MLG",
    "Off",
    "Hdrs L/90",
    "Con/90",
}

BINOMIAL_PRIMITIVES = {
    "pass_completion": ("Ps C", "Pas A"),
    "tackle_success": ("Tck C", "Tck A"),
    "header_win_rate": ("Hdrs", "Hdrs A"),
    "shot_on_target_rate": ("ShT", "Shots"),
    "crossing_completion": ("Cr C", "Cr A"),
    "open_play_crossing_completion": ("OP-Crs C", "OP-Crs A"),
    "penalty_conversion": ("Pens S", "Pens"),
    "penalty_save_rate": ("Pens Saved", "Pens Faced"),
}

RATE_PRIMITIVES = {
    "Ps A/90": "Ps A/90",
    "Pres A/90": "Pres A/90",
    "Pres C/90": "Pres C/90",
    "Poss Won/90": "Poss Won/90",
    "K Tck/90": "K Tck/90",
    "Int/90": "Int/90",
    "Tck/90": "Tck/90",
    "Clr/90": "Clr/90",
    "Blk/90": "Blk/90",
    "Shts Blckd/90": "Shts Blckd/90",
    "Shot/90": "Shot/90",
    "ShT/90": "ShT/90",
    "Pr passes/90": "Pr passes/90",
    "KP/90": "KP/90",
    "OP-KP/90": "OP-KP/90",
    "Ch C/90": "Ch C/90",
    "Asts/90": "Asts/90",
    "Drb/90": "Drb/90",
    "Sprints/90": "Sprints/90",
    "Dist/90": "Dist/90",
    "NP-xG/90": "NP-xG/90",
    "xG/90": "xG/90",
    "xA/90": "xA/90",
    "OP-Crs C/90": "OP-Crs C/90",
    "OP-Crs A/90": "OP-Crs A/90",
    "Cr C/90": "Cr C/90",
    "Crs A/90": "Crs A/90",
    "Hdrs W/90": "Hdrs W/90",
    "Hdrs L/90": "Hdrs L/90",
    "K Hdrs/90": "K Hdrs/90",
    "Aer A/90": "Aer A/90",
    "Saves/90": "Saves/90",
    "xGP/90": "xGP/90",
    "Con/90": "Con/90",
    "Cln/90": "Cln/90",
    "Goals per 90 minutes": "Goals per 90 minutes",
    "CCC": "CCC",
    "Svh": "Svh",
    "Svp": "Svp",
    "Svt": "Svt",
    "Fouls Made": "Fouls Made",
    "Yel": "Yel",
    "Red cards": "Red cards",
    "MLG": "MLG",
    "Off": "Off",
}

NORMAL_PRIMITIVES = {
    "xG/shot": "xG/shot",
    "xG-OP": "xG-OP",
    "xSv %": "xSv %",
    "Sv %": "Sv %",
    "PsP": "PsP",
    "Conv %": "Conv %",
    "finishing_over_expected": None,
    "assist_over_expected": None,
    "shot_quality": None,
    "loss_security": None,
    "discipline_penalty": None,
}

ROLE_ORDER = ["GK", "CB", "FB_WB", "DM", "CM", "AM_W", "ST"]

FAMILY_DEFINITIONS = {
    "GK": {
        "shot_stopping": ["Saves/90", "Sv %", "xSv %", "xGP/90", "penalty_save_rate"],
        "handling_prevention": ["Svh", "Svp", "Svt", "Con/90", "Cln/90"],
        "distribution_security": ["Ps A/90", "pass_completion", "PsP", "Pr passes/90"],
    },
    "CB": {
        "disruption": ["Pres C/90", "Poss Won/90", "K Tck/90", "Int/90", "Tck/90", "tackle_success"],
        "box_defending": ["Clr/90", "Blk/90", "Shts Blckd/90"],
        "aerial_control": ["Hdrs W/90", "header_win_rate", "K Hdrs/90", "Aer A/90", "Hdrs L/90"],
        "progression_security": ["Ps A/90", "pass_completion", "PsP", "Pr passes/90", "Poss Lost/90"],
        "discipline_security": ["Fouls Made", "Yel", "Red cards", "MLG"],
    },
    "FB_WB": {
        "defending": ["Pres C/90", "Poss Won/90", "K Tck/90", "Int/90", "Tck/90", "tackle_success"],
        "progression": ["PsP", "Pr passes/90", "Ps A/90", "pass_completion", "Drb/90"],
        "wide_creation": [
            "OP-Crs C/90",
            "OP-Crs A/90",
            "open_play_crossing_completion",
            "Cr C/90",
            "Crs A/90",
            "crossing_completion",
            "KP/90",
            "OP-KP/90",
            "Ch C/90",
            "xA/90",
        ],
        "engine": ["Sprints/90", "Dist/90"],
        "discipline_security": ["Poss Lost/90", "Fouls Made", "Yel", "Red cards", "MLG"],
    },
    "DM": {
        "ball_winning": ["Pres C/90", "Poss Won/90", "K Tck/90", "Int/90", "Tck/90", "tackle_success"],
        "retention_security": ["pass_completion", "Ps A/90", "Poss Lost/90"],
        "progression": ["PsP", "Pr passes/90", "Ps A/90", "OP-KP/90", "KP/90"],
        "creation": ["Ch C/90", "CCC", "xA/90", "Asts/90"],
        "discipline": ["Fouls Made", "Yel", "Red cards", "MLG"],
    },
    "CM": {
        "retention": ["pass_completion", "Ps A/90", "Poss Lost/90"],
        "progression": ["PsP", "Pr passes/90", "Drb/90"],
        "creation": ["KP/90", "OP-KP/90", "Ch C/90", "CCC", "xA/90", "Asts/90"],
        "ball_winning": ["Pres C/90", "Poss Won/90", "K Tck/90", "Int/90", "Tck/90", "tackle_success"],
        "shot_contribution": [
            "Shot/90",
            "ShT/90",
            "xG/90",
            "NP-xG/90",
            "xG/shot",
            "finishing_over_expected",
        ],
    },
    "AM_W": {
        "threat": [
            "Shot/90",
            "ShT/90",
            "shot_on_target_rate",
            "xG/90",
            "NP-xG/90",
            "xG/shot",
            "finishing_over_expected",
            "Goals per 90 minutes",
        ],
        "creation": ["KP/90", "OP-KP/90", "Ch C/90", "CCC", "xA/90", "Asts/90"],
        "progression_carrying": ["PsP", "Pr passes/90", "Drb/90", "pass_completion", "Ps A/90"],
        "pressing_work": ["Pres A/90", "Pres C/90", "Sprints/90", "Dist/90"],
        "discipline_security": ["Poss Lost/90", "Off", "Fouls Made", "Yel", "MLG"],
    },
    "ST": {
        "threat_volume": ["Shot/90", "ShT/90", "xG/90", "NP-xG/90", "Goals per 90 minutes"],
        "finishing_quality": ["shot_on_target_rate", "Conv %", "xG/shot", "finishing_over_expected"],
        "link_creation": ["KP/90", "OP-KP/90", "Ch C/90", "xA/90", "Asts/90", "pass_completion", "PsP"],
        "pressing": ["Pres A/90", "Pres C/90", "Poss Won/90"],
        "aerial_presence": ["Hdrs W/90", "header_win_rate", "K Hdrs/90", "Aer A/90"],
    },
}

METADATA_COLUMNS = IDENTIFIER_COLUMNS | {"Height"}
